import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#262626",
        secondary: "#e4e2e1",
        "on-surface-variant": "#adaaaa",
        "primary-dim": "#ff7441",
        "on-secondary-fixed-variant": "#5c5b5b",
        "on-primary-container": "#451000",
        "tertiary-container": "#00fdc1",
        "surface-container-high": "#20201f",
        tertiary: "#aaffdc",
        "on-background": "#ffffff",
        "on-secondary": "#525151",
        "inverse-surface": "#fcf9f8",
        "surface-dim": "#0e0e0e",
        "tertiary-fixed-dim": "#00edb4",
        "inverse-on-surface": "#565555",
        "secondary-fixed": "#e4e2e1",
        "on-primary-fixed-variant": "#551600",
        "surface-container-low": "#131313",
        "tertiary-fixed": "#00fdc1",
        background: "#0e0e0e",
        "surface-variant": "#262626",
        "surface-container": "#1a1a1a",
        "on-surface": "#ffffff",
        outline: "#767575",
        "on-tertiary-fixed": "#004734",
        "primary-container": "#ff7948",
        "primary-fixed": "#ff7948",
        "secondary-fixed-dim": "#d6d4d3",
        "inverse-primary": "#ac3600",
        surface: "#0e0e0e",
        "surface-bright": "#2c2c2c",
        "tertiary-dim": "#00edb4",
        "on-primary": "#591800",
        primary: "#ff9069",
        "secondary-dim": "#d6d4d3",
        "on-tertiary": "#00654b",
        "error-dim": "#d7383b",
        "on-tertiary-container": "#005c44",
        "surface-tint": "#ff9069",
        "surface-container-lowest": "#000000",
        "secondary-container": "#474746",
        "error-container": "#9f0519",
        "on-error": "#490006",
        "on-error-container": "#ffa8a3",
        "on-primary-fixed": "#000000",
        "on-secondary-container": "#d2d0cf",
        "on-tertiary-fixed-variant": "#00664c",
        "on-secondary-fixed": "#3f3f3f",
        "primary-fixed-dim": "#fe5e1e",
        "outline-variant": "#484847",
        error: "#ff716c",
      },
      fontFamily: {
        headline: ["var(--font-headline)"],
        body: ["var(--font-body)"],
        label: ["var(--font-label)"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;

